In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import sklearn as skl
import matplotlib.pyplot as plt
from sklearn.feature_selection import SelectKBest, SelectPercentile
from sklearn.feature_selection import chi2
from sklearn.metrics import log_loss, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.cross_validation import cross_val_score, KFold

## 1. Load Training ASM and Bytes Feature Data and Combine

       Run each section in sequence.

In [5]:
# First load the .asm training features and training labels
combined_train_data = pd.read_csv('data/combined-train-data-50percent.csv')
labels = pd.read_csv('data/trainLabels.csv')
#X_asm = train_data_asm.iloc[:,1:]
y = [0]*labels.shape[0]
fnames = train_data_asm['filename']
for i in range(len(y)):
  fname = train_data_asm.loc[i,'filename']
  row = labels[labels['Id'] == fname]
  y[i] = row.iloc[0,1]

In [8]:
train_data_asm.head()

,filename,edx,esi,ah,al,ax,bl,bx,cl,cx,dl,dx,eax,ebp,ebx,ecx,edi,esp,add,al.1,
0,4jKA1GUDv6TMNpPuIxER,4049,9957,60,791,242,393,31,477,135,381,63,17317,10925,4891,8324,7013,3831,1733,331,...
1,4ZBJzEqnW52fFUw0PG3v,539,513,29,152,8,24,2,53,5,30,4,629,133,523,544,527,266,260,22,...
2,6m8NxLfg2MR0nwXFuEq5,427,482,18,163,16,84,0,84,0,130,0,776,235,205,1012,319,163,142,74,...
3,28U1hRkQ6Yl57493ZdXD,51,91,0,0,0,0,0,0,0,0,0,53,81,29,23,111,1,4,0,...
4,45Wy3TxE98HfiXreOCSu,644,726,2,98,89,12,1,157,80,70,84,1337,781,274,911,428,574,290,49,...

In [10]:
# Next load the .byte training features
train_data_byte = pd.read_csv('data/train-malware-features-byte.csv')
train_data_byte.shape

(10870, 3)

In [11]:
train_data_byte.head()

               filename   entropy  filesize
0  e9d614aPtXTmKu7JjfOE  0.476092   8507904
1  0dkuzUXLTEFwW71vP5bS  0.473898   8507904
2  5cVTmPKBAp9Llzbh2MtI  0.357425  11329024
3  80ZfO5UGkLI4Scj3eQwh  0.767887   4443284
4  8kORlw25hI69eu7jEfVy  0.476050   8493056

[5 rows x 3 columns]

In [16]:
train_data_byte[train_data_byte.loc[:,'filename']=='4jKA1GUDv6TMNpPuIxER']

                  filename  entropy  filesize
8484  4jKA1GUDv6TMNpPuIxER  0.77625   1069056

[1 rows x 3 columns]

In [29]:
#combined_train_data = train_data_asm.join(train_data_byte, on='filename', how='outer', lsuffix='.asm', rsuffix='.byte')

In [ ]:
y = [0]*labels.shape[0]
fnames = train_data_asm['filename']
for i in range(len(y)):
  fname = train_data_asm.loc[i,'filename']
  row = labels[labels['Id'] == fname]
  y[i] = row.iloc[0,1]

In [30]:
combined_train_data.head()

,filename,filename.asm,edx,esi,ah,al,ax,bl,bx,cl,cx,dl,dx,eax,ebp,ebx,ecx,edi,esp,add,
0,4jKA1GUDv6TMNpPuIxER,4jKA1GUDv6TMNpPuIxER,4049,9957,60,791,242,393,31,477,135,381,63,17317,10925,4891,8324,7013,3831,1733,...
1,4ZBJzEqnW52fFUw0PG3v,4ZBJzEqnW52fFUw0PG3v,539,513,29,152,8,24,2,53,5,30,4,629,133,523,544,527,266,260,...
2,6m8NxLfg2MR0nwXFuEq5,6m8NxLfg2MR0nwXFuEq5,427,482,18,163,16,84,0,84,0,130,0,776,235,205,1012,319,163,142,...
3,28U1hRkQ6Yl57493ZdXD,28U1hRkQ6Yl57493ZdXD,51,91,0,0,0,0,0,0,0,0,0,53,81,29,23,111,1,4,...
4,45Wy3TxE98HfiXreOCSu,45Wy3TxE98HfiXreOCSu,644,726,2,98,89,12,1,157,80,70,84,1337,781,274,911,428,574,290,...

In [31]:
print(combined_train_data.iloc[0,:])

filename        4jKA1GUDv6TMNpPuIxER
filename.asm    4jKA1GUDv6TMNpPuIxER
edx                             4049
esi                             9957
ah                                60
al                               791
ax                               242
bl                               393
bx                                31
cl                               477
cx                               135
dl                               381
dx                                63
eax                            17317
ebp                            10925
...
WinMain              0
unk                203
cookie             292
off                588
void                 0
HWND                 0
int.1              227
entry                0
__imp_               0
.rdata:            370
.data:             196
.text:           62816
filename.byte      NaN
entropy            NaN
filesize           NaN
Name: 0, Length: 106, dtype: object

In [24]:
help(pd.DataFrame.join)

Help on method join in module pandas.core.frame:

join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False) unbound pandas.core.frame.DataFrame method
    Join columns with other DataFrame either on index or on a key
    column. Efficiently Join multiple DataFrame objects by index at once by
    passing a list.

    Parameters
    ----------
    other : DataFrame, Series with name field set, or list of DataFrame
        Index should be similar to one of the columns in this one. If a
        Series is passed, its name attribute must be set, and that will be
        used as the column name in the resulting joined DataFrame
    on : column name, tuple/list of column names, or array-like
        Column(s) to use for joining, otherwise join on index. If multiples
        columns given, the passed DataFrame must have a MultiIndex. Can
        pass an array as the join key if not already contained in the
        calling DataFrame. Like an Excel VLOOKUP operation
    how : {'left', 'right', 'outer', 'inner'}
        How to handle indexes of the two objects. Default: 'left'
        for joining on index, None otherwise

        * left: use calling frame's index
        * right: use input frame's index
        * outer: form union of indexes
        * inner: use intersection of indexes
    lsuffix : string
        Suffix to use from left frame's overlapping columns
    rsuffix : string
        Suffix to use from right frame's overlapping columns
    sort : boolean, default False
        Order result DataFrame lexicographically by the join key. If False,
        preserves the index order of the calling (left) DataFrame

    Notes
    -----
    on, lsuffix, and rsuffix options are not supported when passing a list
    of DataFrame objects

    Returns
    -------
    joined : DataFrame

## 2. Model Selection On The Combined Training ASM/Byte Data Using GridSearchCV
    Run each section in sequence

(10873, 1007)

In [22]:
# Extract the reduced feature set from the full test feature set
test_data_reduced = test_data.loc[:,column_names]

In [23]:
test_data_reduced.head()

,filename,edx,esi,ah,al,ax,bl,bx,cl,cx,dl,dx,eax,ebp,ebx,ecx,edi,esp,add,al.1,
0,N0DQkgaq9wjO1fJLn2ME,382,664,0,76,107,36,0,79,57,68,40,841,354,220,741,300,257,169,39,...
1,VuvdGbYitmxa05lHrPnT,129,101,2,1,0,0,0,0,0,0,0,253,199,122,124,357,243,129,0,...
2,NRUDJPSHu4dAyFjzLIg9,351,329,7,135,12,35,4,61,27,79,33,427,207,267,427,286,250,165,54,...
3,ZmdXvIh5qHCOyJPwiE6g,303,248,0,6,1,9,3,42,1,3,4,436,412,145,338,170,57,49,2,...
4,rcb7LxNP6itSDnwgh3Km,99,75,2,1,0,0,0,0,0,0,0,137,148,83,98,226,272,186,0,...

In [24]:
test_data_reduced.to_csv('data/test-malware-features-asm-reduced.csv', index=False)

## 3. Run ExtraTreeClassifiers With 10-Fold Cross Validation

In [47]:
def run_cv(X,y, clf):

    # Construct a kfolds object
    kf = KFold(len(y),n_folds=10,shuffle=True)
    y_prob = np.zeros((len(y),9))
    y_pred = np.zeros(len(y))
    
    # Iterate through folds
    for train_index, test_index in kf:
        print(test_index, train_index)
        X_train = X.loc[train_index,:]
        X_test = X.loc[test_index,:]
        y_train = y[train_index]

        clf.fit(X_train,y_train)
        y_prob[test_index] = clf.predict_proba(X_test)
        y_pred[test_index] = clf.predict(X_test)
    
    return y_prob, y_pred

In [41]:
ytrain = np.array(y)

In [50]:
X = data_reduced.iloc[:,1:]
X.shape

(10868, 101)

In [56]:
clf1 = ExtraTreesClassifier(n_estimators=1000, max_features=None, min_samples_leaf=1, min_samples_split=9, n_jobs=4, criterion='gini')
p1, pred1 = run_cv(X,ytrain,clf1)
print "logloss = %.3f" % log_loss(y, p1)
print "score = %.3f" % accuracy_score(ytrain, pred1)
cm = confusion_matrix(y, pred1)
print(cm)

(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9782,)
(9782,)
logloss = 0.043
[[1535    0    1    1    0    0    0    4    0]
 [   7 2469    1    0    0    1    0    0    0]
 [   0    0 2942    0    0    0    0    0    0]
 [   0    0    1  470    0    0    0    4    0]
 [   1    1    0    0   40    0    0    0    0]
 [   3    1    0    1    0  741    0    2    3]
 [   0    0    0    0    0    0  398    0    0]
 [  26    1    1    2    0    2    1 1195    0]
 [   4    0    0    0    0    2    0    2 1005]]

In [57]:
clf2 = ExtraTreesClassifier(n_estimators=500, max_features=None, min_samples_leaf=1, min_samples_split=9, n_jobs=4, criterion='gini')
p2, pred2 = run_cv(X,ytrain,clf2)
print "logloss = %.3f" % log_loss(y, p2)
print "score = %.3f" % accuracy_score(ytrain, pred2)
cm = confusion_matrix(y, pred2)
print(cm)

(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9782,)
(9782,)
logloss = 0.041
[[1535    0    1    1    0    0    0    4    0]
 [   7 2468    2    0    0    0    0    0    1]
 [   0    0 2942    0    0    0    0    0    0]
 [   0    0    1  470    0    0    0    4    0]
 [   1    1    0    0   40    0    0    0    0]
 [   3    1    0    1    0  741    0    3    2]
 [   0    0    0    0    0    0  398    0    0]
 [  30    0    1    3    0    2    2 1190    0]
 [   4    0    0    0    0    1    0    3 1005]]

In [58]:
clf3 = ExtraTreesClassifier(n_estimators=250, max_features=None, min_samples_leaf=1, min_samples_split=9, n_jobs=4, criterion='gini')
p3, pred3 = run_cv(X,ytrain,clf3)
print "logloss = %.3f" % log_loss(y, p3)
print "score = %.3f" % accuracy_score(ytrain, pred3)
cm = confusion_matrix(y, pred3)
print(cm)

(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9782,)
(9782,)
logloss = 0.044
[[1534    0    1    1    0    0    0    5    0]
 [   6 2469    1    0    0    2    0    0    0]
 [   0    0 2942    0    0    0    0    0    0]
 [   0    0    1  469    0    0    0    5    0]
 [   1    1    0    0   40    0    0    0    0]
 [   3    1    0    1    0  741    0    2    3]
 [   0    0    0    0    0    0  398    0    0]
 [  26    1    1    5    1    3    2 1189    0]
 [   3    0    0    0    0    2    0    2 1006]]

In [59]:
clf4 = ExtraTreesClassifier(n_estimators=2000, max_features=None, min_samples_leaf=2, min_samples_split=3, n_jobs=4, criterion='gini')
p4, pred4 = run_cv(X,ytrain,clf4)
print "logloss = %.3f" % log_loss(y, p4)
print "score = %.3f" % accuracy_score(ytrain, pred4)
cm = confusion_matrix(y, pred4)
print(cm)

(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9782,)
(9782,)
logloss = 0.040
[[1535    0    1    1    0    0    0    4    0]
 [   9 2466    2    0    0    1    0    0    0]
 [   0    0 2939    0    0    0    0    3    0]
 [   0    0    1  473    0    0    0    1    0]
 [   1    2    0    0   38    0    0    1    0]
 [   3    1    0    1    0  741    0    2    3]
 [   0    0    0    0    0    0  397    1    0]
 [  31    0    1    4    0    2    1 1189    0]
 [   4    0    0    0    0    2    0    2 1005]]

In [64]:
clf5 = ExtraTreesClassifier(n_estimators=1000, n_jobs=4, criterion='gini')
p5, pred5 = run_cv(X,ytrain,clf5)
print "logloss = %.4f" % log_loss(y, p5)
print "score = %.4f" % accuracy_score(ytrain, pred5)
cm = confusion_matrix(y, pred5)
print(cm)

(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9782,)
(9782,)
logloss = 0.0533
score = 0.9930
[[1535    0    1    1    0    0    0    4    0]
 [   7 2468    1    1    0    1    0    0    0]
 [   0    0 2938    0    0    0    0    4    0]
 [   1    0    0  473    0    0    0    1    0]
 [   1    1    0    0   40    0    0    0    0]
 [   3    1    0    1    0  743    0    2    1]
 [   0    0    0    0    0    0  396    2    0]
 [  27    0    0    3    0    2    1 1195    0]
 [   4    0    0    0    0    2    0    3 1004]]

In [65]:
clf6 = ExtraTreesClassifier(n_estimators=2000, n_jobs=4, criterion='gini')
p6, pred6 = run_cv(X,ytrain,clf6)
print "logloss = %.4f" % log_loss(y, p6)
print "score = %.4f" % accuracy_score(ytrain, pred6)
cm = confusion_matrix(y, pred6)
print(cm)

(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9781,)
(9782,)
(9782,)
logloss = 0.0509
score = 0.9928
[[1534    0    1    1    0    0    0    5    0]
 [   9 2467    1    0    0    1    0    0    0]
 [   0    0 2941    0    0    0    0    1    0]
 [   1    0    0  473    0    0    0    1    0]
 [   1    1    0    0   39    0    0    1    0]
 [   3    1    0    3    0  741    0    2    1]
 [   0    0    0    0    0    0  396    2    0]
 [  27    0    1    3    0    1    1 1194    1]
 [   4    0    0    0    0    2    0    2 1005]]

## 4. TEST/EXPERIMENT CODE ONLY

In [ ]:
# go through the features and delete any that sum to less than 200
colsum = X.sum(axis=0, numeric_only=True)

In [ ]:
zerocols = colsum[(colsum[:] == 0)]
zerocols

In [ ]:
zerocols = colsum[(colsum[:] < 110)]
zerocols.shape

In [ ]:
reduceX = X
for col in reduceX.columns:
  if sum(reduceX[col]) < 100:
    del reduceX[col]
    
reduceX.shape

In [ ]:
skb = SelectKBest(chi2, k=20)
X_kbestnew = skb.fit_transform(X, y)
X_kbestnew.shape