In [1]:
import numpy as np
import scipy as sp
import pandas as pd
import sklearn as skl
import matplotlib.pyplot as plt
import xgboost as xbg
from sklearn.cross_validation import train_test_split, cross_val_score, KFold
from sklearn.metrics import log_loss, confusion_matrix, accuracy_score

In [3]:
data = pd.read_csv('data/final-combined-train-data-30percent.csv')
labels = pd.read_csv('data/sorted-train-labels.csv')

In [4]:
data.head()

,filename,edx,esi,es,ds,ss,cs,ah,al,ax,...,ASM_964,ASM_972,ASM_977,ASM_990,trainmean,trainstd,trainmin,trainmax,traintotal,trainlogtotal
0,01IsoiSMh5gxyDYTl4CB,750,496,3,0,0,0,8,224,49,...,32,49,53,10,586.160040,12877.609022,0.0,288961.0,2.181176e+12,28.410885
1,01SuzwMJEIXsK7A8dQbl,1121,24,3,1,4,2,6,22,7,...,48,9,9,116,5.908549,60.063976,0.0,1068.0,3.790235e+05,12.845354
2,01azqd4InC7m9JpocGv5,1493,1900,0,0,0,0,1,398,0,...,48,9,9,116,7.002982,64.756651,0.0,1173.0,5.319434e+05,13.184292
3,01jsnpXSAlgw6aPeDxrU,525,4,0,0,0,0,0,0,0,...,48,9,9,116,327.150099,3278.958529,0.0,81305.0,8.721682e+10,25.191663
4,01kcPWA9K2BOxQeS5Rju,23,35,0,0,0,0,0,3,0,...,48,89,32,71,5.932406,60.189034,0.0,1068.0,3.813462e+05,12.851463

In [5]:
labels.head()

                     Id  Class
0  01IsoiSMh5gxyDYTl4CB      2
1  01SuzwMJEIXsK7A8dQbl      8
2  01azqd4InC7m9JpocGv5      9
3  01jsnpXSAlgw6aPeDxrU      9
4  01kcPWA9K2BOxQeS5Rju      1

In [21]:
X = data.iloc[:,1:]
y = np.array(labels.iloc[:,1:] - 1)
y

array([[1],
       [7],
       [8],
       ...,
       [3],
       [3],
       [3]], dtype=int64)

In [7]:
def run_cv(X,y, clf):

    # Construct a kfolds object
    kf = KFold(len(y),n_folds=10,shuffle=True)
    y_prob = np.zeros((len(y),9))
    y_pred = np.zeros(len(y))
    
    # Iterate through folds
    for train_index, test_index in kf:
        print(train_index, test_index)
        X_train = X.loc[train_index,:]
        X_test = X.loc[test_index,:]
        y_train = y[train_index]

        clf.fit(X_train,y_train)
        y_prob[test_index] = clf.predict_proba(X_test)
        y_pred[test_index] = clf.predict(X_test)
    
    return y_prob, y_pred

In [30]:
xgclf = xgb.XGBClassifier(n_estimators=1000, objective="multi:softmax")
prob, pred = run_cv(X,y,xgclf)
print("logloss: {:.4f}".format(log_loss(y, prob)))
print("accuracy: {:.4f}".format(accuracy_score(y, pred)))
cm = confusion_matrix(y, pred)
print(cm)

/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/home/derek/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/label.py:108: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

accuracy: 0.9981
[[1540    0    0    0    0    1    0    0    0]
 [   2 2475    0    1    0    0    0    0    0]
 [   0    0 2941    0    0    0    1    0    0]
 [   0    0    0  474    0    1    0    0    0]
 [   1    0    0    0   41    0    0    0    0]
 [   4    0    0    0    1  746    0    0    0]
 [   0    0    0    0    0    0  398    0    0]
 [   0    0    0    0    0    0    0 1227    1]
 [   0    0    0    0    0    0    0    8 1005]]

In [35]:
print("logloss: {:.4f}".format(log_loss(y, prob)))

logloss: 0.0080

In [49]:
labelarr = y.ravel().tolist()

In [ ]:
labelarr

In [51]:
type(labelarr)

list